#!/usr/bin/env node
/**
 * This file is auto-generated by CLI Maker.
 * Do not edit manually.
 */

import { setupCLI } from './cli.js';
import { DummyHandler } from './handler.js';

async function main() {
  const handler = new DummyHandler();
  const program = setupCLI(handler);
  
  await program.parseAsync(process.argv);
}

main().catch((error) => {
  console.error('Error:', error);
  process.exit(1);
});
