/**
 * This file is auto-generated by CLI Maker.
 * Do not edit manually.
 */

export interface Testapp2Params {
  ra: string;
}

export interface FirstSubcmdParams {
  subargstr: string;
  subargbool?: boolean;
}

export interface SecondSubcmdParams {
}

